### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zopetoolkit#8]
The following packages are not yet compatible with Python 3.6:

- [x] zopefoundation/zope.dottedname#4
- [x] zopefoundation/zope.testing#16
- [x] zopefoundation/zope.testrunner#45
- [x] zopefoundation/zope.index#8

All other ZTK packages need a change in setup.py declaring Python 3.6 compatibility once it is finally released.

**Comment by tseaver** [comment]
The `zope.dottedname` "failure" is an issue *here* (`zopetoolkit` is somehow trying to run docstrings in sub-package's README files).

**Comment by tseaver** [comment]
ZTK packages without explicit 3.6. support:

- [ ] zope.authentication
- [ ] zope.browsermenu
- [ ] zope.browserpage
- [ ] zope.browserresource
- [ ] zope.browser
- [ ] zope.cachedescriptors
- [ ] zope.catalog
- [ ] zope.component
- [ ] zope.componentvocabulary
- [ ] zope.container
- [ ] zope.contentprovider
- [ ] zope.contenttype
- [ ] zope.copypastemove
- [ ] zope.copy
- [ ] zope.datetime
- [ ] zope.deferredimport
- [ ] zope.deprecation
- [ ] zope.dublincore
- [ ] zope.error
- [ ] zope.event
- [ ] zope.filerepresentation
- [ ] zope.formlib
- [ ] zope.hookable
- [ ] zope.i18n
- [ ] zope.intid
- [ ] zope.lifecycleevent
- [ ] zope.location
- [ ] zope.login
- [ ] zope.minmax
- [ ] zope.pagetemplate
- [ ] zope.password
- [ ] zope.principalannotation
- [ ] zope.principalregistry
- [ ] zope.processlifetime
- [ ] zope.ptresource
- [ ] zope.ramcache
- [ ] zope.schema
- [ ] zope.securitypolicy
- [ ] zope.sendmail
- [ ] zope.session
- [ ] zope.site
- [ ] zope.size
- [ ] zope.structuredtext
- [ ] zope.tales
- [ ] zope.tal
- [ ] zope.traversing
- [ ] zope.viewlet

**Comment by hannosch** [comment]
See also https://zope3.pov.lt/py3/ as an overview.

**Comment by mgedmin** [comment]
BTW there's a hidden feature that lets you filter by package name prefix, e.g. https://zope3.pov.lt/py3/?filter=zope.

(I see I've unhid it for https://zope3.pov.lt/py3/travis.html but forgot to unhide it for index.html.)

**Comment by icemac** [comment]
After the packages which where not compatible with 3.6 where fixed I added #20 to officially test Python 3.6 for all ZTK packages.

**Comment by jamadden** [comment]
We're getting pretty close! Everything that's still outstanding on the list now has open PRs ready for review.

**Comment by jamadden** [comment]
As of now, everything on the list provided has been released to PyPI with the 3.6 classifier added. In most cases, the 3.3 classifier is removed. Even more excitingly, in most cases test coverage has also reached 100%!

Thanks to all the contributors and reviewers!

Can we close this issue now @icemac ?

**Comment by sallner** [comment]
Thanks @jamadden for pushing this milestone forward. It was a lot of work!

**Comment by icemac** [comment]
@jamadden Thank you for your hard work solving this issue and doing way more than pure Python 3.6 updates.
